export enum BookGenre {
  Fiction = 'Fiction',
  Mystery = 'Mystery',
  Fantasy = 'Fantasy',
  ScienceFiction = 'ScienceFiction',
  Romance = 'Romance',
  Horror = 'Horror',
  NonFiction = 'NonFiction',
  Biography = 'Biography',
  Poetry = 'Poetry',
  HistoricalFiction = 'HistoricalFiction',
  Children = 'Children',
  Young = 'Young',
  Adult = 'Adult',
  Thriller = 'Thriller',
  SelfHelp = 'Self-Help',
  Business = 'Business',
  Science = 'Science',
  Travel = 'Travel',
  Cookbooks = 'Cookbooks',
  Philosophy = 'Philosophy',
  Other = 'Other',
}
